[workspace]
resolver = "2"
members = [
    "blade-graphics",
    "blade-macros",
]
exclude = []

[workspace.dependencies]
naga = { git = "https://github.com/kvark/naga", branch = "bindings", features = ["wgsl-in", "span", "validate"] }

[lib]

[package]
name = "blade"
description = "Sharp and simple graphics library"
version = "0.0.1"
edition = "2021"
rust-version = "1.65"
keywords = ["graphics"]
license = "MIT"
repository = "https://github.com/kvark/blade"
readme = "docs/README.md"

[features]

[dependencies]
blade-macros = { version = "0.0.1", path = "blade-macros" }
blade-graphics = { version = "0.0.1", path = "blade-graphics" }

[dev-dependencies]
bytemuck = { version = "1", features = ["derive"] }
egui = { version = "0.20", features = ["bytemuck"] }
egui-winit = "0.20"
env_logger = "0.9"
naga = { workspace = true }
rand = "0.8"
winit = "0.27"
