[workspace]
resolver = "2"
members = [
    "blade-graphics",
    "blade-macros",
    "run-wasm",
]
exclude = []

[workspace.dependencies]
naga = { version = "0.11", features = ["wgsl-in", "span", "validate"] }
web-sys = "0.3.60"

[lib]

[package]
name = "blade"
description = "Sharp and simple graphics library"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
keywords = ["graphics"]
license = "MIT"
repository = "https://github.com/kvark/blade"
readme = "docs/README.md"

[features]

[dependencies]
blade-macros = { version = "0.1.0", path = "blade-macros" }
blade-graphics = { version = "0.1.0", path = "blade-graphics" }

[dev-dependencies]
bytemuck = { version = "1", features = ["derive"] }
egui = { version = "0.20", features = ["bytemuck"] }
naga = { workspace = true }
nanorand = { version = "0.7", default-features = false, features = ["wyrand"] }
winit = "0.27"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
egui-winit = "0.20"
env_logger = "0.9"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2"
web-sys = { workspace = true, features = ["Window"] }
